/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageComponent from "../ImageComponent/ImageComponent";

const ProfileSection = () => {
  return (
    <section>
      <ImageComponent
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3315b0291b21b91aa3687b2f1245695c64fa5e74a022403455ef2a4dd9874646?apiKey=e16c345da64e4f1b8d3ee529c6533a56&&apiKey=e16c345da64e4f1b8d3ee529c6533a56"
        alt="User profile"
      />
    </section>
  );
};

export default ProfileSection;
