/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./GlassContainer.module.css";
import SupplierPage from "./SupplierPage/SupplierPage"

const GlassContainer = () => {
  return (
    <section className={styles.container}>
      <div className={styles.glassPanel} />
      <SupplierPage/>
    </section>
  );
};

export default GlassContainer;
