/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageComponent.module.css";

const ImageComponent = ({ src, alt }) => {
  return (
    <img loading="lazy" src={src} alt={alt} className={styles.profileImage} />
  );
};

export default ImageComponent;
