/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SupplierPage.module.css";
import Navigation from "./Navigation";
import SupplierForm from "./SupplierForm";

const SupplierPage = () => {
  return (
    <div className={styles.container}>
      <header className={styles.hero}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/acc7f2e7743db4484ecf60bb18438adb4db26fc183deb6b8d71a176d4eaa0cfb?apiKey=e9e3b1cf1c6c49d689c28c861602b444&&apiKey=e9e3b1cf1c6c49d689c28c861602b444"
          alt=""
          className={styles.heroImage}
        />
        <Navigation />
        <div className={styles.heroContent}>
          <h1 className={styles.heroTitle}>
            Lorem ipsum dolor sit <br /> <br /> amet,{" "}
          </h1>
          <p className={styles.heroDescription}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec
            odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla
            quis sem at nibh elementum imperdiet. Duis sagittis ipsum.
          </p>
        </div>
      </header>

      <section className={styles.supplierSection}>
        <div className={styles.supplierContent}>
          <h2 className={styles.supplierTitle}>BE A SUPPLIER</h2>
          <p className={styles.supplierSubtitle}>MAKE A CHANGE</p>
          <SupplierForm />
        </div>
      </section>

      <section className={styles.communitySection}>
        <h2>COMMUNITY FRIDGE AROUND YOU</h2>
      </section>

      <section className={styles.mapSection}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/77d678963ed67c812dd636781000c298cf854c1e14cc2586d7d247cf1f0f872d?apiKey=e9e3b1cf1c6c49d689c28c861602b444&&apiKey=e9e3b1cf1c6c49d689c28c861602b444"
          alt="Community fridge map"
          className={styles.mapImage}
        />
      </section>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default SupplierPage;
